[package]
name = "dam-remote-todoist"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "the Todoist remote helper for dam"

[lib]
path = "src/lib.rs"

[[bin]]
name = "dam-remote-todoist"
path = "src/main.rs"

[dependencies]
dam-protocol = { path = "../dam-protocol" }
serde.workspace = true
serde_json.workspace = true
ureq.workspace = true
