[package]
name = "dam-adapters"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
libc.workspace = true
dam-domain = { path = "../dam-domain" }
dam-application = { path = "../dam-application" }
dam-protocol = { path = "../dam-protocol" }
jiff.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
getrandom.workspace = true
tempfile.workspace = true

[dev-dependencies]
dam-application = { path = "../dam-application", features = ["testing"] }
